### ISSUE TITLE
no interface is detected

### ISSUE THREAD

**Issue by mczerski** [xrucka/bluetooth-manager-dbus#10]
Hi,
I can't get this working. I'musing bluez 5.43 with --experimental on raspberry pi 3. the tinyB transport worked without problem (well, there was one problem thats why I'm trying this transport, but it was detecting the adapter and ble device).  Nothing is discovered, and when I enable debug messages for trasnport I get only this line repeating:
[INFO ] [h.manager.transport.dbus.BluezFactory] - Found running bluetooth daemon, connecting & populating...

**Comment by xrucka** [comment]
Hi, thanks for the report; are you running the rewrite_all branch, or master? If you're running master, please try rewrite_all instead. Furthermore, does entering "list" in bluetoothctl print out your adapter?

**Comment by mczerski** [comment]
I was runing master. Now I tried reqrite_all and I see that there is an error in the openhab log:
```
2019-01-09 23:36:09.930 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.eclipse.smarthome.binding.bluetooth.transport.dbus-1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: organovabanka.org.eclipse.smarthome.binding.bluetooth.transport.dbus [248]
  Unresolved requirement: Import-Package: org.sputnikdev.bluetooth

	at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) [?:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [9:org.apache.felix.fileinstall:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [9:org.apache.felix.fileinstall:3.6.4]

```
It is possible that when I was using master branch there was the same error ... So this is probably the cause of the problem.
In bluetoothctl I can see my adapter in list command output.
