### ISSUE TITLE
Null pointer exception upon post-start adapter plug-in

### ISSUE THREAD

**Issue by xrucka** [xrucka/bluetooth-manager-dbus#4]
Background:
1) OpenHab fresh start without adapter plugged in.
2) Wait for about-dinner-time minutes
3) Plug-in adapter

`
openhab> Exception in thread "Thread-62" java.lang.NullPointerException                                                                                                 
        at cz.organovabanka.bluetooth.manager.transport.dbus.BluezDevice.updateURL(BluezDevice.java:183)
        at cz.organovabanka.bluetooth.manager.transport.dbus.BluezDevice.<init>(BluezDevice.java:96)
        at cz.organovabanka.bluetooth.manager.transport.dbus.BluezContext.getManagedDevice(BluezContext.java:240)
        at cz.organovabanka.bluetooth.manager.transport.dbus.BluezContext.getManagedDevice(BluezContext.java:219)
        at cz.organovabanka.bluetooth.manager.transport.dbus.BluezFactory.probeAdd(BluezFactory.java:146)
        at cz.organovabanka.bluetooth.manager.transport.dbus.BluezFactory$AddedHandler.handle(BluezFactory.java:110)
        at cz.organovabanka.bluetooth.manager.transport.dbus.BluezFactory$AddedHandler.handle(BluezFactory.java:106)
        at org.freedesktop.dbus.AbstractConnection$2.run(AbstractConnection.java:976)
        at org.freedesktop.dbus.AbstractConnection$WorkerThread.run(AbstractConnection.java:202)
`

**Comment by xrucka** [comment]
Form of race caused by asynchronous execution of dbus signal handlers. Should be fixed.
